name: codey_do
description: "**CodeyDo** is a personal learning project built with **Flutter**.   The purpose of this app is to put into practice the concepts and tools I'm learning as I grow in my Flutter development journey."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

#    assets:
#      - images/a_dot_burr.jpeg

#    fonts:
#      - family: Schyler
#        fonts:
#          - asset: fonts/Schyler-Regular.ttf
  
  
  
  
  
  
  
  
  
  
